<a href="https://colab.research.google.com/github/DaxPatel10/DATA-SCIENSE/blob/main/pandas_for__DS_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pandas series

In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d ={1:10,2:20,3:30}

In [4]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

data frame

In [7]:
import numpy as np
import pandas as pd

In [13]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]}
df =pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [23]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ['Name', 'Age', 'City', 'Salary']
df2 = pd.DataFrame(data_list, columns = columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

selection and indextion of columns

In [24]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [27]:
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [28]:
df2["Designation"] = ["Doctor","Eng.","Doctor","Eng."]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

removing

In [30]:
df2.drop("City",axis = 1,inplace = True)

In [31]:
df2

    Name  Age  Salary Designation
0   John   28   65000      Doctor
1   Anna   34   70000        Eng.
2  Peter   29   62000      Doctor
3  Linda   42   85000        Eng.

selecting rows

In [33]:
df2

    Name  Age  Salary Designation
0   John   28   65000      Doctor
1   Anna   34   70000        Eng.
2  Peter   29   62000      Doctor
3  Linda   42   85000        Eng.

In [34]:
df2.loc[0]

Name             John
Age                28
Salary          65000
Designation    Doctor
Name: 0, dtype: object

In [35]:
df.iloc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

selecting subset of row and columns

In [39]:
df2

    Name  Age  Salary Designation
0   John   28   65000      Doctor
1   Anna   34   70000        Eng.
2  Peter   29   62000      Doctor
3  Linda   42   85000        Eng.

In [41]:
df.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

conditions

In [42]:
df2

    Name  Age  Salary Designation
0   John   28   65000      Doctor
1   Anna   34   70000        Eng.
2  Peter   29   62000      Doctor
3  Linda   42   85000        Eng.

In [44]:
df2[df2["Age"]>30]

    Name  Age  Salary Designation
1   Anna   34   70000        Eng.
3  Linda   42   85000        Eng.

In [47]:
df2[(df2["Age"]>30)&(df2["Salary"]== 85000)]

    Name  Age  Salary Designation
3  Linda   42   85000        Eng.